module.exports = {
  id: 'no-frills',
  name: 'No Frills',
  baseUrl: 'https://www.nofrills.ca',
  strategy: 'browser',
  browser: {
    searchUrl: (term) =>
      `https://www.nofrills.ca/en/search?search-bar=${encodeURIComponent(term)}`,
    selectors: {
      products: [
        '.product-tile',
        '.product-item',
        '.product-card',
        '[data-testid*="product"]',
        '.grid-item',
        '.search-result-item',
        '[class*="ProductCard"]',
        '[class*="product-card"]',
        '[class*="product-item"]',
        '.chakra-box[role="group"]',
        '.css-yyn1h',
      ],
      names: [
        '[data-testid="product-name"]',
        '[data-testid="product-title"]',
        '.product-name',
        '.product-title',
        'h3',
        'h4',
        '.title',
        '[class*="name"]',
        '[class*="title"]',
        '.chakra-heading',
      ],
      prices: [
        '[data-testid="price"]',
        '[data-testid="current-price"]',
        '[data-testid="regular-price"]',
        '[data-testid="sale-price"]',
        '.price',
        '.current-price',
        '.regular-price',
        '.sale-price',
        '[class*="price"]',
        '.cost',
        '.chakra-text[data-testid*="price"]',
      ],
      brands: [
        '[data-testid="brand"]',
        '[data-testid="product-brand"]',
        '.brand',
        '.product-brand',
        '[class*="brand"]',
      ],
      packageSizes: [
        '[data-testid="size"]',
        '[data-testid="package-size"]',
        '[data-testid="product-size"]',
        '.size',
        '.package-size',
        '.product-size',
        '[class*="size"]',
      ],
      images: [
        '[data-testid="product-image"] img',
        '.product-image img',
        '.product-img img',
        'img[alt*="product"]',
        'img',
        '.chakra-image',
      ],
      links: [
        'a[href*="/product"]',
        'a[href*="/p/"]',
        'a[href*="/item"]',
        '.product-link',
        'a',
        '.chakra-linkbox__overlay',
      ],
      originalPrices: [
        '[data-testid="was-price"]',
        '[data-testid="original-price"]',
        '.was-price',
        '.original-price',
        '[class*="was-price"]',
        '[class*="original-price"]',
      ],
    },
    waitDelay: { min: 3000, max: 5000 },
  },
};
