module.exports = {
  id: 'save-on-foods',
  name: 'Save On Foods',
  baseUrl: 'https://www.saveonfoods.com',
  strategy: 'browser',
  browser: {
    searchUrl: (term) =>
      `https://www.saveonfoods.com/sm/planning/rsid/1982/results?q=${encodeURIComponent(term)}`,
    selectors: {
      products: [
        '.ProductCardWrapper--6uxd5a',
        '[data-testid*="ProductCardWrapper"]',
        '[class*="ProductCardWrapper"]',
        '.product-tile',
        '.product-item',
        '.product-card',
        '[data-testid*="product"]',
        '.grid-item',
        '.search-result-item',
        '[class*="ProductCard"]',
        '[class*="product-card"]',
        '[class*="product-item"]',
        '.product-container',
        '.item-container',
        '[data-qa*="product"]',
        '.product-wrapper',
      ],
      names: [
        '[data-testid*="ProductNameTestId"]',
        '.ProductCardTitle--1ln1u3g div',
        '.AriaProductTitleParagraph--1yc7f4f:first-of-type',
        '[data-testid="product-name"]',
        '[data-testid="product-title"]',
        '.product-name',
        '.product-title',
        'h3',
        'h4',
        'h2',
        '.title',
        '[class*="name"]',
        '[class*="title"]',
        '.item-name',
        '.product-description h3',
        '.product-description h4',
      ],
      prices: [
        '.ProductCardPrice--1sznkcp',
        '[data-testid="productCardPricing-div-testId"] span:first-child span',
        '[data-testid="price"]',
        '[data-testid="current-price"]',
        '[data-testid="regular-price"]',
        '[data-testid="sale-price"]',
        '.price',
        '.current-price',
        '.regular-price',
        '.sale-price',
        '[class*="price"]',
        '.cost',
        '.item-price',
        '.product-price',
        '.price-current',
        '.price-regular',
      ],
      brands: [
        '.ProductAQABrand--9zdrc2',
        '[data-testid="ProductCardAQABrand"]',
        '[data-testid="brand"]',
        '[data-testid="product-brand"]',
        '.brand',
        '.product-brand',
        '[class*="brand"]',
        '.brand-name',
      ],
      packageSizes: [
        '[data-testid="size"]',
        '[data-testid="package-size"]',
        '[data-testid="product-size"]',
        '.size',
        '.package-size',
        '.product-size',
        '[class*="size"]',
        '.item-size',
        '.unit-size',
      ],
      images: [
        '.ProductCardImageWrapper--klzjiv img',
        '[data-testid*="productCardImage"] img',
        '[data-testid="product-image"] img',
        '.product-image img',
        '.product-img img',
        'img[alt*="product"]',
        'img[alt*="Product"]',
        'img',
        '.item-image img',
        '.product-photo img',
      ],
      links: [
        '.ProductCardHiddenLink--v3c62m',
        'a[href*="/product/"]',
        'a[href*="/product"]',
        'a[href*="/p/"]',
        'a[href*="/item"]',
        '.product-link',
        'a',
        '.item-link',
        '.product-url',
      ],
      originalPrices: [
        '.WasPrice--1iwg7oj',
        '[data-testid="was-price"]',
        '[data-testid="original-price"]',
        '.was-price',
        '.original-price',
        '[class*="was-price"]',
        '[class*="original-price"]',
        '.price-was',
        '.strikethrough-price',
      ],
    },
    waitDelay: { min: 3000, max: 5000 },
    extractOverrides: {
      cleanNameSuffix: 'Open product description',
    },
  },
};
