module.exports = {
  id: 'walmart',
  name: 'Walmart',
  baseUrl: 'https://www.walmart.ca',
  strategy: 'browser',
  browser: {
    searchUrl: (term) =>
      `https://www.walmart.ca/en/search?q=${encodeURIComponent(term)}`,
    selectors: {
      products: [
        '[data-automation-id="product-tile"]',
        '.mb0.ph1.pa0-xl.bb.b--near-white.w-25',
        '[class*="product-tile"]',
        '.product-tile',
        '.product-item',
        '.product-card',
        '[data-testid*="product"]',
        '.grid-item',
        '.search-result-item',
        '[class*="ProductCard"]',
        '[class*="product-card"]',
        '[class*="product-item"]',
        '.product-container',
        '.item-container',
        '[data-qa*="product"]',
        '.product-wrapper',
      ],
      names: [
        '[data-automation-id="product-title"]',
        'span[data-automation-id="product-title"]',
        '[data-testid="product-name"]',
        '[data-testid="product-title"]',
        '.product-name',
        '.product-title',
        'h3',
        'h4',
        'h2',
        '.title',
        '[class*="name"]',
        '[class*="title"]',
        '.item-name',
        '.product-description h3',
        '.product-description h4',
      ],
      prices: [
        '[data-automation-id="product-price"] .b',
        '[data-automation-id="product-price"]',
        '.price-current .price-display',
        '[data-testid="price"]',
        '[data-testid="current-price"]',
        '[data-testid="regular-price"]',
        '[data-testid="sale-price"]',
        '.price',
        '.current-price',
        '.regular-price',
        '.sale-price',
        '[class*="price"]',
        '.cost',
        '.item-price',
        '.product-price',
        '.price-current',
        '.price-regular',
      ],
      brands: [
        '[data-automation-id="product-brand"]',
        '[data-testid="brand"]',
        '[data-testid="product-brand"]',
        '.brand',
        '.product-brand',
        '[class*="brand"]',
        '.brand-name',
      ],
      packageSizes: [
        '[data-automation-id="product-size"]',
        '[data-testid="size"]',
        '[data-testid="package-size"]',
        '[data-testid="product-size"]',
        '.size',
        '.package-size',
        '.product-size',
        '[class*="size"]',
        '.item-size',
        '.unit-size',
      ],
      images: [
        '[data-automation-id="product-image"] img',
        'img[data-automation-id="product-image"]',
        '[data-testid="product-image"] img',
        '.product-image img',
        '.product-img img',
        'img[alt*="product"]',
        'img[alt*="Product"]',
        'img',
        '.item-image img',
        '.product-photo img',
      ],
      links: [
        'a[data-automation-id="product-title"]',
        'a[href*="/ip/"]',
        'a[href*="/product/"]',
        'a[href*="/product"]',
        'a[href*="/p/"]',
        'a[href*="/item"]',
        '.product-link',
        'a',
        '.item-link',
        '.product-url',
      ],
      originalPrices: [
        '[data-automation-id="product-price"] .strike',
        '[data-automation-id="was-price"]',
        '[data-testid="was-price"]',
        '[data-testid="original-price"]',
        '.was-price',
        '.original-price',
        '[class*="was-price"]',
        '[class*="original-price"]',
        '.price-was',
        '.strikethrough-price',
        '.strike',
      ],
    },
    waitDelay: { min: 2000, max: 4000 },
  },
};
